### ISSUE TITLE
Does not work for 1.19.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ExpensiveKoala/Clear-Water#1]
[crash-2022-08-23_14.45.46-fml.txt](https://github.com/ExpensiveKoala/Clear-Water/files/9410230/crash-2022-08-23_14.45.46-fml.txt)

**Comment by LolJohn11** [comment]
Same here
[crash-2022-10-14_12.31.52-fml.txt](https://github.com/ExpensiveKoala/Clear-Water/files/9784546/crash-2022-10-14_12.31.52-fml.txt)

**Comment by ExpensiveKoala** [comment]
Fixed with latest release
